# Generated by Django 2.1.5 on 2019-03-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=255)),
                ('patente_chasis', models.CharField(max_length=255)),
                ('patente_acoplado', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transportista.Transportista')),
            ],
        ),
    ]
