# Generated by Django 2.1.5 on 2019-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='patente_acoplado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='patente_chasis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
