# Generated by Django 2.1.5 on 2019-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0003_auto_20190328_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='patente_acoplado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='patente_chasis',
            field=models.CharField(max_length=255),
        ),
    ]
