data:{
    'fecha': full,
    'numero': carta.numero,
    'ctg': carta.ctg,
    'renspa': carta.renspa,
    'conforme': carta.conforme,
    'intermediario': carta.intermediario,
    'corredor_comprador': carta.corredor_comprador,
    'mercado_a_termino': carta.mercado_a_termino,
    'corredor_vendedor': carta.corredor_vendedor,
    'entregador': carta.entregador,
    'destinatario': carta.destinatario,
    'destino': carta.destino,
    'intermediario_flete': carta.intermediario_flete,
    'transportista': carta.transportista,
    'chofer': carta.chofer,
    'grano': carta.grano,
    'tipo': carta.tipo,
    'cosecha': carta.cosecha,
    'contrato': carta.contrato,
    'pesada_en_destino': carta.pesada_en_destino,
    'kgs_estimados': carta.kgs_estimados,
    'declaracion_calidad': carta.declaracion_calidad,
    'condicional': carta.condicional,
    'peso_bruto': carta.peso_bruto,
    'peso_tara': carta.peso_tara,
    'peso_neto': carta.peso_neto,
    'observaciones': carta.observaciones,
    'direccion_procedencia': carta.direccion_procedencia,
    'localidad_procedencia': carta.localidad_procedencia,
    'provincia_procedencia': carta.provincia_procedencia,
    'kilometros': carta.kilometros,
    'tarifa': carta.tarifa,
    'tarifa_referencia': carta.tarifa,
    'declaracion_juarada_nombre': carta.declaracion_juarada_nombre,
    'declaracion_juarada_dni': carta.declaracion_juarada_dni,
    'docfile_url': "http://localhost:8000/media/cp_nuevas/" + carta.docfile.name
 }