# Generated by Django 2.1.5 on 2019-03-07 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0005_auto_20190301_1730'),
        ('remitentecomercial', '0001_initial'),
        ('transportista', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mat', '0001_initial'),
        ('entregador', '0001_initial'),
        ('destinatario', '0001_initial'),
        ('intermediarioflete', '0001_initial'),
        ('destino', '0001_initial'),
        ('intermediario', '0001_initial'),
        ('corredor', '0001_initial'),
        ('chofer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaDePorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('ctg', models.CharField(max_length=255)),
                ('renspa', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('grano', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('cosecha', models.CharField(max_length=255)),
                ('contrato', models.CharField(max_length=255)),
                ('pesada_en_destino', models.BooleanField()),
                ('kgs_estimados', models.BooleanField()),
                ('declaracion_calidad', models.BooleanField()),
                ('conforme', models.BooleanField()),
                ('condicional', models.BooleanField()),
                ('peso_bruto', models.CharField(max_length=255)),
                ('peso_tara', models.CharField(max_length=255)),
                ('peso_neto', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
                ('direccion_procedencia', models.CharField(max_length=255)),
                ('localidad_procedencia', models.CharField(max_length=255)),
                ('provincia_procedencia', models.CharField(max_length=255)),
                ('kilometros', models.CharField(max_length=255)),
                ('tarifa', models.CharField(max_length=255)),
                ('tarifa_referencia', models.CharField(max_length=255)),
                ('declaracion_juarada_nombre', models.CharField(max_length=255)),
                ('declaracion_juarada_dni', models.CharField(max_length=255)),
                ('docfile', models.FileField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chofer.Chofer')),
                ('corredor_comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corredorC', to='corredor.Corredor')),
                ('corredor_vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corredorV', to='corredor.Corredor')),
                ('destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destinatario.Destinatario')),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destino.Destino')),
                ('entregador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entregador.Entregador')),
                ('intermediario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intermediario.Intermediario')),
                ('intermediario_flete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intermediarioflete.IntermediarioFlete')),
                ('mercado_a_termino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mat.MercadoATermino')),
                ('remitente_comercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remitentecomercial.RemitenteComercial')),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
                ('transportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transportista.Transportista')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
