# Generated by Django 2.1.5 on 2019-03-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartadeporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chofer.Chofer'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='contrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='corredor_comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corredorC', to='corredor.Corredor'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='corredor_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corredorV', to='corredor.Corredor'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='cosecha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='ctg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='declaracion_juarada_dni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='declaracion_juarada_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinatario.Destinatario'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destino.Destino'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='direccion_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entregador.Entregador'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='grano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='intermediario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intermediario.Intermediario'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='intermediario_flete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intermediarioflete.IntermediarioFlete'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='kilometros',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='localidad_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='mercado_a_termino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mat.MercadoATermino'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='peso_bruto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='peso_neto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='peso_tara',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='provincia_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='remitente_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remitentecomercial.RemitenteComercial'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='renspa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='tarifa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='tarifa_referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportista.Transportista'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
