# Generated by Django 2.1.5 on 2019-04-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadeporte', '0002_auto_20190307_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='cp_nuevas/'),
        ),
    ]
