# Generated by Django 2.1.5 on 2019-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadeporte', '0003_auto_20190418_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='cp_nuevas'),
        ),
    ]
