# Generated by Django 2.1.5 on 2019-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadeporte', '0004_auto_20190427_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='condicional',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='conforme',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='declaracion_calidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='kgs_estimados',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
