# Generated by Django 2.1.5 on 2019-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadeporte', '0005_auto_20190509_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='pesada_en_destino',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
